### ISSUE TITLE
pass url to js to get results

### ISSUE THREAD

**Issue by foxpcteam** [Muhnad/a11y-checker#31]
HI,
the checker check the page where the js file is included. but how we can pass some url to js file and get the results without including the file to each page.

Thanks

**Comment by Muhnad** [comment]
Hi @foxpcteam 

unfortunately, this option does not exist yet, maybe in the new update will add it.

but you can make this to check all pages:
- if you have a main script file included in all .html files you can add this lines to main script file to include the a11y.js in all pages.

```js
const scr = document.createElement('script');
scr.src = 'https://cdn.rawgit.com/Muhnad/a11y-checker/master/a11y.js';
document.body.appendChild(scr);
```
