### ISSUE TITLE
Missing id:  & class: 

### ISSUE THREAD

**Issue by ahmadajmi** [Muhnad/a11y-checker#9]
For two checks, the `id` and `class` are missing in the console message.

```
⚠️ Should add role=form OR role=search to form id:  & class: 
⚠️ Should add aria-labelledby to form id:  & class:
```

![screen shot 2016-12-02 at 9 18 07 am](https://cloud.githubusercontent.com/assets/626005/20825952/4bc3a238-b870-11e6-8731-91c12fea0d3c.png)

Testing on this page: http://maxima.aspirethemes.com/

Great work Muhannad 👍

**Comment by Muhnad** [comment]
That's because you don't set any id or class to this form, maybe I'll change it to get the code instead of id or class.

![image](https://cloud.githubusercontent.com/assets/13405108/20859647/f7b587b2-b96c-11e6-8acc-62c05f289257.png)

Thanks, Ahmed :green_heart:

**Comment by ahmadajmi** [comment]
Yea, your suggestion would be great, so it will help knowing the specific element easily 👍

**Comment by Muhnad** [comment]
can download now the file and see the code not only id&class :smile:

**Comment by ahmadajmi** [comment]
@Muhnad Perfect 👍
